site_name: Sumeh DQ — Unified Data Quality Framework
site_description: "Library for Data Quality checks"
site_author: "Demetrius Albuquerque"

theme:
  name: material
  logo: img/sumeh.svg
  favicon: img/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)"
      logo: img/sumeh.svg
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      logo: img/sumeh.svg
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - include-markdown:
      basepath: ../
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            line_length: 88
            merge_init_into_class: true
            separate_signature: true
            show_docstring_description: true

nav:
  - home: index.md
  - quickstart: quickstart.md
  - cli: sumeh/cli.md
  - core:
    - config: sumeh/core/config.md
    - utils: sumeh/core/utils.md
  - engines:
    - engine overview: sumeh/engines/engines.md
    - bigquery: sumeh/engines/bigquery.md
    - dask: sumeh/engines/dask.md
    - duckDB: sumeh/engines/duckdb.md
    - pandas: sumeh/engines/pandas.md
    - polars: sumeh/engines/polars.md
    - pyspark: sumeh/engines/pyspark.md
  - generators:
    - generator: sumeh/generators/generator.md
    - dialects:
      - base: sumeh/generators/dialects/base.md
      - athena: sumeh/generators/dialects/athena.md
      - bigquery: sumeh/generators/dialects/bigquery.md
      - databricks: sumeh/generators/dialects/databricks.md
      - duckdb: sumeh/generators/dialects/duckdb.md
      - mysql: sumeh/generators/dialects/mysql.md
      - postgres: sumeh/generators/dialects/postgres.md
      - redshift: sumeh/generators/dialects/redshift.md
      - snowflake: sumeh/generators/dialects/snowflake.md
      - sqlite: sumeh/generators/dialects/sqlite.md
  - dash: sumeh/dash/index.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables